"""update

Revision ID: 446ba2aeabdd
Revises: 460a8937176e
Create Date: 2023-05-15 07:05:12.235447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446ba2aeabdd'
down_revision = '460a8937176e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.TIME(),
               nullable=True)

    with op.batch_alter_table('outgo', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outgo', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.TIME(),
               nullable=False)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.TIME(),
               nullable=False)

    # ### end Alembic commands ###
