"""Updated models

Revision ID: 460a8937176e
Revises: 
Create Date: 2023-05-14 21:02:58.451909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460a8937176e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('outgo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('outgo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('update_at')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
